histproject/battles/urls.py
from django.urls import path, include

from histproject.battles.views import ListBattleView, CreateBattleView, DetailBattleView, UpdateBattleView, \
    DeleteBattleView, CreateCountryView

urlpatterns = [
    path('', ListBattleView.as_view(), name='battle_list'),
    path('country/', CreateCountryView.as_view(), name='country'),
    path('new/', CreateBattleView.as_view(), name='battle_create'),
    path('<int:pk>/', include([
        path('', DetailBattleView.as_view(), name='battle_detail'),
        path('edit/', UpdateBattleView.as_view(), name='battle_edit'),
        path('delete/', DeleteBattleView.as_view(), name='battle_delete'),
    ]))
]

histproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('histproject.accounts.urls')),
    path('', include('histproject.common.urls')),
    path('battle/', include('histproject.battles.urls')),
    path('statistics/', include('histproject.visual.urls')),
    path('context/', include('histproject.context.urls')),
    path('social/', include('histproject.social_share.urls')),
    path('post/', include('histproject.posts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

histproject/battles/models.py
from django.db import models

from histproject.battles.choices import ChoiceResult
from histproject.battles.validators import validate_only_letters, clean_bg


class Country(models.Model):
    name = models.CharField(
        max_length=255,
        unique=True,
        verbose_name='Име',
        validators=[clean_bg, validate_only_letters]
    )

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class Battle(models.Model):
    name = models.CharField(
        max_length=200,
        blank=False,
        null=False,
        validators=[clean_bg]
    )
    date = models.DateField()
    location = models.CharField(max_length=200)
    countries_involved = models.ManyToManyField(
        to=Country,
        related_name="countries"
    )
    result = models.CharField(
        max_length=100,
        choices=ChoiceResult.choices
    )
    description = models.TextField(blank=True, null=True)
    latitude = models.DecimalField(max_digits=9, decimal_places=6)
    longitude = models.DecimalField(max_digits=9, decimal_places=6)
    image_url = models.URLField(
        blank=True,
        null=True,
    )
    class Meta:
        ordering = ('date',)

    def __str__(self):
        return f"{self.name} ({self.date})"

histproject/battles/forms.py
from django import forms

from histproject.battles.models import Battle, Country


class BattleBaseForm(forms.ModelForm):
    class Meta:
        model = Battle
        fields = '__all__'
        widgets ={
            'date': forms.DateInput(attrs={'placeholder': 'Y-M-d'}),
            'name': forms.TextInput(attrs={'placeholder': 'NAME battlefield'}),
            'latitude':forms.TextInput(attrs={'placeholder': '00.0000'}),
            'longitude':forms.TextInput(attrs={'placeholder': 'longitude'}),
            'image_url': forms.URLInput(attrs={'placeholder': 'https://'}),
            'location': forms.TextInput(attrs={'placeholder': 'location'}),
            'description': forms.Textarea(attrs={'placeholder': 'description'})
        }

class BattleDetailForm(BattleBaseForm):
    pass

class BattleEditForm(BattleBaseForm):
    pass

class BattleDeleteForm(BattleBaseForm):
    pass

class CountryForm(forms.ModelForm):
    class Meta:
        model = Country
        fields =('name',)

histproject/battles/views.py
from django.contrib import messages
from django.core.paginator import Paginator

from django.db.models import Avg, Q
from django.shortcuts import  redirect
from django.urls import reverse_lazy

from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView

from histproject.battles.forms import BattleBaseForm, BattleEditForm, CountryForm
from histproject.battles.models import Battle, Country
from histproject.posts.forms import CommentForm, RatingForm
from histproject.posts.models import Rating


class ListBattleView(ListView):
    model = Battle
    template_name = 'battles/battle_list.html'
    context_object_name = 'battles'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['Battle'] = Battle.objects.all()
        return context

    def get_queryset(self):
        query = self.request.GET.get('search', '')
        if query:
            return Battle.objects.filter(
                Q(location__icontains=query) | Q(countries_involved__name__icontains=query)
            ).distinct()
        return Battle.objects.all()

class DetailBattleView(DetailView):
    model = Battle
    template_name = 'battles/battle_detail.html'
    context_object_name = 'battle'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentForm()
        context['rating_form'] = RatingForm()


        comments = self.object.comments.all()
        paginator = Paginator(comments, 2)  # Показваме по 2 коментара на страница
        page_number = self.request.GET.get('page', 1)
        page_obj = paginator.get_page(page_number)
        context['comments'] = page_obj

        avg = Rating.objects.filter(battle=self.object).aggregate(Avg('score'))
        context['avg_score'] = avg['score__avg'] or 0
        context['page_obj'] = page_obj
        print(context)
        return context


    def post(self, request, *args, **kwargs):
        self.object = self.get_object()

        if 'content' in request.POST:
            return self.handle_comment(request)
        elif 'score' in request.POST:
            return self.handle_rating(request)
        return redirect('battle_detail', pk=self.object.pk)

    def handle_comment(self, request):
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.battle = self.object
            comment.user = request.user
            comment.save()
            print(comment)
            messages.success(request, 'Коментарът е добавен успешно!')
        else:
            messages.error(request, 'Грешка при добавяне на коментар.')
        return redirect('battle_detail', pk=self.object.pk)

    def handle_rating(self, request):
        rating_form = RatingForm(request.POST)
        if rating_form.is_valid():
            existing_rating = Rating.objects.filter(battle=self.object, user=request.user).first()

            if existing_rating:
                messages.error(request, 'Вече сте оценили тази битка.')
                return redirect('battle_detail', pk=self.object.pk)
            rating = rating_form.save(commit=False)
            rating.battle = self.object
            rating.user = request.user
            rating.save()
            messages.success(request, 'Рейтингът е добавен успешно!')
        else:
            messages.error(request, 'Грешка при добавяне на рейтинг.')
        return redirect('battle_detail', pk=self.object.pk)






class CreateBattleView(CreateView):
    model = Battle
    template_name = 'battles/battle_create.html'
    form_class = BattleBaseForm
    success_url = reverse_lazy('battle_list')


class UpdateBattleView(UpdateView):
    model = Battle
    form_class = BattleEditForm
    template_name = 'battles/battle_edit.html'
    success_url = reverse_lazy('battle_list')


class DeleteBattleView(DeleteView):
    model = Battle
    template_name = 'battles/battle_delete.html'
    success_url = reverse_lazy('battle_list')


class CreateCountryView(CreateView):
    model = Country
    form_class = CountryForm
    template_name = 'battles/country_create.html'
    success_url = reverse_lazy('battle_create')

templates/battles/battle_create.html
{% load static %}
<!DOCTYPE html>  
<html lang="bg">  
<head>  
    <meta charset="UTF-8">
 <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>{% if form.instance.pk %}Редактиране{% else %}Добавяне{% endif %} на битка</title>  
</head>

<body>
<div class="battle-create">
<h1>{% if form.instance.pk %}Редактиране{% else %}Добавяне{% endif %} на битка</h1>  
<form method="POST">  
    {% csrf_token %}  
    {{ form.as_p }}  
    <button type="submit">Запази</button>  
</form>
    <a href="{% url 'country' %}">Добави страна</a>
</div>
</body>

</html>

templates/battles/battle_delete.html
{% load  static %}
<!DOCTYPE html>  
<html lang="bg">  
<head>  
    <meta charset="UTF-8">  
    <title>Потвърдете изтриването</title>
     <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>  
<body>
<div id=" battle-delete">
    <h1>Сигурни ли сте, че искате да изтриете "{{ battle }}"?</h1>
        <form method="POST">  
            {% csrf_token %}  
            <button type="submit">Да, изтрий</button>  
        </form>  
    <a href="{% url 'battle_list' %}">Отказ</a>
    </div>
</body>  
</html>

templates/battles/battle_detail.html
{% extends 'base.html' %}
{% block content %}
<body>
<title>Детайли за битка</title>
        {% if messages %}  
<div class="messages">  
        {% for message in messages %}  
            <div class="alert {% if message.tags %}{{ message.tags }}{% endif %}">  
                {{ message }}  
            </div>  
        {% endfor %}  
    </div>  
{% endif %}
<div class="container-battle">  
        <h1>{{ object.title }}</h1>  
        <p class="description"><strong>Описание:</strong> {{ object.description }}</p> 
        <p>Участващи страни:</p>
            {% for country in battle.countries_involved.all %}
            <ul class="country">  
                   
                    <li>{{ country.name }}</li>
            </ul> 
            {% endfor %} 
        <p>{{ battle.get_result_display }}</p>
        <p><strong>Дата:</strong> {{ object.date }}</p>  
        
        <!-- Можете да добавите и снимка на битката, ако имате такова поле -->  
        {% if object.image_url %}  
            <img src="{{ battle.image_url }}" alt="{{ object.title }}" />  
        {% endif %}  
        {%  if user.is_superuser or user.is_staff %}
        <ul class="battle">
            <li><a href="{% url 'battle_edit' battle.pk %}">Промени</a></li>
            <li><a href="{% url 'battle_delete' battle.pk %}">Изтрий</a></li>
        </ul>
        {% endif %}
        <h2>Коментари:</h2>  
        <div class="comments">  
            {% for comment in comments %}  
                <div class="comment">  
                    <p><strong>{{ comment.user.username }}</strong>: {{ comment.content }}</p>  
                    <p><small>Побликуван на: {{ comment.created_at }}</small></p>
                {% if comment.user == user %}
                    <div class="comment-edit-delete">
                <a href="{% url 'comment_edit' comment.pk %}">Редактирай</a>
                <a href="{% url 'comment_delete' comment.pk %}">Изтрий</a> 
                    </div>
                {% endif %}
                </div>  
            {% empty %}  
                <p>Няма все още коментари.</p>  
            {% endfor %}  
        </div>  
        {% if comments.has_other_pages %}  
    <div class="pagination">  
      <span class="step-links">  
        {% if comments.has_previous %}  
          <a href="?page=1">&laquo; Първа</a>  
          <a href="?page={{ comments.previous_page_number }}">Предишна</a>  
        {% endif %}  

        <span class="current">  
          Страница {{ comments.number }} от {{ comments.paginator.num_pages }}  
        </span>  

        {% if comments.has_next %}  
          <a href="?page={{ comments.next_page_number }}">Следваща</a>  
          <a href="?page={{ comments.paginator.num_pages }}">Последна &raquo;</a>  
        {% endif %}  
      </span>  
    </div>  
  {% endif %}  
    
  <h2>Оценка: {{ avg_score|floatformat:1 }}</h2>
    <div class="comment-battle">
        
        {% if user.is_authenticated %}
            <h3>Оставете коментар:</h3> 
        <form method="post" action="{% url 'battle_detail' battle.pk %}">  
            {% csrf_token %}  
            {{ comment_form.as_p }}  
            <button type="submit">Изпрати коментар</button>
            
        </form> 
        
    </div>
            <p>Средна Оценка: {{ avg_score }}</p>
        <div class="scroll-battle">
        <h3>Оценете битката:</h3>  
        <form method="post" {% url 'battle_detail' battle.pk %}>  
            {% csrf_token %}  
            {{ rating_form.as_p }}  
            <button type="submit">Оцени</button>  
        </form>
            {% else %}
        <p>За да оставите коментар и оценка, моля, <a class="battle-comment" href="{% url 'register' %}">регистрирайте се</a> или <a class="battle-comment" href="{% url 'login' %}">влезте</a>.</p>
        {% endif %}
        </div>
    </div>

</body>
{% endblock %}

templates/battles/battle_edit.html
{% extends 'base.html' %}
{% block content %}
    <div class="battle-edit">
    <form method="post" >
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn-battle-edit" type="submit">Промени</button>
    </form>
    
    </div>
    
{% endblock %}

templates/battles/battle_list.html
{% extends 'base.html' %}
{% block content %}
    <h1>Битки</h1>  
    <form class="battles-s" method="GET">  
        <input type="text" name="search" placeholder="Търсене..." value="{{ request.GET.search }}">  
        <button type="submit">Търси</button>
    </form>
    <div class="battle-create-a">
        {% if user.is_staff %}
        <a href="{% url 'battle_create' %}">Добави нова битка</a> 
        {% endif %}
    </div>
    <div class="battle-detail">
        <h2>БИТКИ</h2> 
            {% for b in battles %}
            <ul class="battle">
                <li><a href="{% url 'battle_detail' b.pk %}">{{ b }}</a> </li>
            </ul>
                
                {% empty %}
                <p>Няма намерени битки.</p>
    </div>
            {% endfor %}
         {% if not page_obj.has_next and page_obj.number == 1 %}
                <p>That's the only page</p>
            {% else %}
                <div class="pagination">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; first</a>
                            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}
                
                        <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>
                
                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">next</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
                </div>
            {% endif %}
{% endblock %}

templates/battles/country_create.html
<body>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">добави</button>
</form>
</body>

templates/battles/statistics.html
{% extends 'base.html' %}
{% block content %}
    <div class="statistic">
<h1>Статистика на битки</h1>  

<h2>Брой битки по години</h2>  
<img src="data:image/png;base64,{{ statistics_image }}" alt="Графика на битките по години">  


<div>  
    {{ map_html|safe }}  
</div>  

<a href="{% url 'battle_list' %}">Назад към списъка с битки</a> 
    </div>
{% endblock %}